ftdi: use correct sleep
We get warning:
ftdi-gpio.c:191:9: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]

This is fixed by adding correct header, but the problem is that usleep
is deprecated so update to use sleep as well

Signed-off-by: Vinod Koul <vkoul@kernel.org>